#pragma once

#include <SDL.h>
enum InputKeys
{
	UP = SDL_SCANCODE_W,
	DOWN = SDL_SCANCODE_S,
	LEFT = SDL_SCANCODE_A,
	RIGHT = SDL_SCANCODE_D,
	INTERACTION = SDL_SCANCODE_E,
	ONE = SDL_SCANCODE_1,
	TWO = SDL_SCANCODE_2,
	THREE = SDL_SCANCODE_3,
	FOUR = SDL_SCANCODE_4,
	FIVE = SDL_SCANCODE_5,
	SIX = SDL_SCANCODE_6,
	INVENTORY = SDL_SCANCODE_TAB,
	ATTACK = SDL_SCANCODE_SPACE,
	ESCAPE = SDL_SCANCODE_ESCAPE
};